// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/yari/dev/ykb/qmk/yama.png --output /home/yari/dev/qmk/keyboards/yama/graphics --format rgb888 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_yama_length;
extern const uint8_t  gfx_yama[4573];
